version: '3.1'
services:
  db:
    container_name: node-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: holaroot
      MYSQL_DATABASE: tech
      MYSQL_USER: sting
      MYSQL_PASSWORD: holamundo
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    external: true
