version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: holaroot
      MYSQL_DATABASE: tech
      MYSQL_USER: sting
      MYSQL_PASSWORD: holamundo
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  mysql-data:
    external: true
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
